In [15]:
import pandas as pd
import numpy as np
from dataAccessor import get_intraday, get_daily, get_singletime
# from config import av_api_key
from util import compare_df_cols, TIME_MAP, trading_datemap
from datetime import date
import pandas_market_calendars as mcal

In [170]:
class backTester():
    
    def __init__(self, order_book = None, stat_mode = None):
        self.orders = pd.DataFrame(columns=['order_id','ticker','order_type','qty','exec_date','exec_time','exec_inftime','exec_fulldate'])
        self.stat_mode = stat_mode

        self.MAX_TRADE_DAYS = 180
        
        if order_book: 
            self.add_orders(order_book)
            
    def add_orders(self,order_book):

        # generate exec_fulldate
        order_book['exec_inftime'] = order_book['exec_time'].map(TIME_MAP)
        # order_book['exec_fulldate'] = order_book['exec_date'] + order_book['exec_time'].map(TIME_MAP)
        order_book['exec_fulldate'] = order_book['exec_date'] + order_book['exec_inftime'].combine_first(order_book['exec_time'])
        
        # adds orders to order book
        a_not_b = compare_df_cols(self.orders, order_book)
        assert a_not_b.empty
        
        to_add = order_book[['order_id','order_type','qty','exec_time','exec_date','ticker','exec_inftime','exec_fulldate']]
        self.orders = pd.concat([self.orders, order_book])

    def get_pfolio_exec(self, stat_mode):
        
        self.orders['exec_price']=self.orders.apply(
            lambda row: get_singletime(
                ticker=row['ticker'],date=row['exec_date'],dot=row['exec_time'],price_freq=stat_mode
            )['price'].values[0], 
            axis=1
        )

    def get_pfolio_fwd(self, stat_mode):
        if stat_mode == 'daily':

            # get forward prices of each order's ticker starting at exec date
            self.pfolio_prices = self.orders.copy()

            self.pfolio_prices['fwd'] = self.pfolio_prices.apply(
                lambda row: get_daily(
                    row['ticker'],
                    start_date=row['exec_date'],
                    end_date=row['exec_date']+pd.Timedelta(days=self.MAX_TRADE_DAYS)
                ), 
                axis = 1
            )

            # unnest, creates df of prices with associated order_id on each row
            fwd_prices = (
                pd.concat(self.pfolio_prices.set_index(self.orders.columns.tolist()).pop('fwd').to_dict())
                .rename_axis(tuple(self.orders.rename(columns={'ticker':'exec_ticker'}).columns.tolist() + ['new']))
                # # .rename_axis(('order_id','new'))
                .reset_index(level=[i for i in range(len(self.orders.columns.tolist()))])
                .reset_index(drop=True)
            )
            assert fwd_prices['exec_ticker'].equals(fwd_prices['ticker'])
            
            fwd_prices.drop(columns=['exec_ticker'],inplace=True)
            
            # changes open/close columns into one column called trade_price
            fwd_prices_open = fwd_prices[
                ['order_id','ticker','order_type','qty','exec_date','exec_time','exec_inftime','exec_fulldate','exec_price','open','date']
            ]
            fwd_prices_open['fwd_inftime'] = pd.Timedelta(hours=9,minutes=30)
            fwd_prices_open['fwd_fulldate'] = fwd_prices_open['date'] + fwd_prices_open['fwd_inftime'] 
            fwd_prices_open.rename(columns={'date':'fwd_date','open':'fwd_price'}, inplace=True)

            fwd_prices_close = fwd_prices[
                ['order_id','ticker','order_type','qty','exec_date','exec_time','exec_inftime','exec_fulldate','exec_price','close','date']
            ]
            fwd_prices_close['fwd_inftime'] = pd.Timedelta(hours=16)
            fwd_prices_close['fwd_fulldate'] = fwd_prices_close['date'] + fwd_prices_close['fwd_inftime']
            fwd_prices_close.rename(columns={'date':'fwd_date','close':'fwd_price'}, inplace=True)
            
            self.pfolio_prices = pd.concat([fwd_prices_open, fwd_prices_close])
            print(self.pfolio_prices.shape)
            self.pfolio_prices = self.pfolio_prices.loc[self.pfolio_prices.fwd_fulldate >= self.pfolio_prices.exec_fulldate]
            print(self.pfolio_prices.shape)
            
        elif stat_mode == 'intraday':
            raise NotImplementedError('TODO')

    def calc_pfolio_stats(self):
        # avg return over time
        # pct positive at time points
        # sharpe ratio of trades
    
    def trade(self, stat_mode = None):
        if stat_mode:
            self.stat_mode = stat_mode
        # get data
        if stat_mode == 'daily':
            # get exec prices
            self.get_pfolio_exec(self.stat_mode)
            # get forward prices
            self.get_pfolio_fwd(self.stat_mode)
        
        elif stat_mode == 'intraday':
            raise NotImplementedError('TODO')

        # calculate positions
        self.pfolio_prices['fwd_cumu_ret'] = self.pfolio_prices['fwd_price'] / self.pfolio_prices['exec_price']

        t_datemap = trading_datemap(
            start_date = self.pfolio_prices.fwd_date.min(),
            end_date = self.pfolio_prices.fwd_date.max()
        )

        self.pfolio_prices['date_delta'] = ( 
            self.pfolio_prices['fwd_date'].dt.date.map(t_datemap) - self.pfolio_prices['exec_fulldate'].dt.date.map(t_datemap) 
        ) + (
            (self.pfolio_prices['fwd_inftime'] - self.pfolio_prices['exec_inftime']) / np.timedelta64(1, 'D')
        )

        # generate pfolio stats
    

    def results(self):
        raise NotImplementedError('TODO')

In [171]:
b = backTester()

In [172]:
test_orders = pd.DataFrame(
    [
        [1,'buy',1,'open',pd.to_datetime('2023-08-04'),'IBM'],
        [1,'buy',1,'close',pd.to_datetime('2022-03-08'),'GE']
    ], 
    index = [1, 2],
    columns=['order_id','order_type','qty','exec_time','exec_date','ticker']
)
test_orders

   order_id order_type  qty exec_time  exec_date ticker
1         1        buy    1      open 2023-08-04    IBM
2         1        buy    1     close 2022-03-08     GE

In [173]:
b.add_orders(test_orders)

In [174]:
b.orders

,order_id,ticker,order_type,qty,exec_date,exec_time,exec_inftime,exec_fulldate
1,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00
2,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00

In [175]:
b.trade(stat_mode = 'daily')

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
(280, 13)
(279, 13)

C:\Users\danie\AppData\Local\Temp\ipykernel_24932\2884490700.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fwd_prices_open['fwd_inftime'] = pd.Timedelta(hours=9,minutes=30)
C:\Users\danie\AppData\Local\Temp\ipykernel_24932\2884490700.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fwd_prices_open['fwd_fulldate'] = fwd_prices_open['date'] + fwd_prices_open['fwd_inftime']
C:\Users\danie\AppData\Local\Temp\ipykernel_24932\2884490700.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fwd_prices_open.rename(columns={'date':'fwd_date','open':'fwd_price'}, inplace=True)
C:\Users\danie\AppData\Local\Temp\ipykernel_24932\2884490700.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fwd_prices_close['fwd_inftime'] = pd.Timedelta(hours=16)
C:\Users\danie\AppData\Local\Temp\ipykernel_24932\2884490700.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fwd_prices_close['fwd_fulldate'] = fwd_prices_close['date'] + fwd_prices_close['fwd_inftime']
C:\Users\danie\AppData\Local\Temp\ipykernel_24932\2884490700.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fwd_prices_close.rename(columns={'date':'fwd_date','close':'fwd_price'}, inplace=True)

In [176]:
b.orders

,order_id,ticker,order_type,qty,exec_date,exec_time,exec_inftime,exec_fulldate,exec_price
1,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996
2,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431

In [177]:
b.pfolio_prices

,order_id,ticker,order_type,qty,exec_date,exec_time,exec_inftime,exec_fulldate,exec_price,fwd_price,fwd_date,fwd_inftime,fwd_fulldate,fwd_cumu_ret,date_delta
0,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,145.089996,2023-08-04,0 days 09:30:00,2023-08-04 09:30:00,1.000000,0.0
1,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,145.000000,2023-08-07,0 days 09:30:00,2023-08-07 09:30:00,0.999380,1.0
2,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,145.699997,2023-08-08,0 days 09:30:00,2023-08-08 09:30:00,1.004204,2.0
3,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,144.940002,2023-08-09,0 days 09:30:00,2023-08-09 09:30:00,0.998966,3.0
4,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,143.039993,2023-08-10,0 days 09:30:00,2023-08-10 09:30:00,0.985871,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,59.367680,2022-08-29,0 days 16:00:00,2022-08-29 16:00:00,0.862734,120.0
136,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,58.649494,2022-08-30,0 days 16:00:00,2022-08-30 16:00:00,0.852297,121.0
137,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,57.330212,2022-08-31,0 days 16:00:00,2022-08-31 16:00:00,0.833125,122.0
138,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,57.049179,2022-09-01,0 days 16:00:00,2022-09-01 16:00:00,0.829041,123.0
139,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,56.541763,2022-09-02,0 days 16:00:00,2022-09-02 16:00:00,0.821668,124.0

In [178]:
b.pfolio_prices.head(50)

,order_id,ticker,order_type,qty,exec_date,exec_time,exec_inftime,exec_fulldate,exec_price,fwd_price,fwd_date,fwd_inftime,fwd_fulldate,fwd_cumu_ret,date_delta
0,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,145.089996,2023-08-04,0 days 09:30:00,2023-08-04 09:30:00,1.000000,0.000000
1,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,145.000000,2023-08-07,0 days 09:30:00,2023-08-07 09:30:00,0.999380,1.000000
2,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,145.699997,2023-08-08,0 days 09:30:00,2023-08-08 09:30:00,1.004204,2.000000
3,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,144.940002,2023-08-09,0 days 09:30:00,2023-08-09 09:30:00,0.998966,3.000000
4,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,143.039993,2023-08-10,0 days 09:30:00,2023-08-10 09:30:00,0.985871,4.000000
5,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,143.119995,2023-08-11,0 days 09:30:00,2023-08-11 09:30:00,0.986422,5.000000
6,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,143.050003,2023-08-14,0 days 09:30:00,2023-08-14 09:30:00,0.985940,6.000000
7,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,141.500000,2023-08-15,0 days 09:30:00,2023-08-15 09:30:00,0.975257,7.000000
8,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,141.699997,2023-08-16,0 days 09:30:00,2023-08-16 09:30:00,0.976635,8.000000
9,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,141.009995,2023-08-17,0 days 09:30:00,2023-08-17 09:30:00,0.971880,9.000000
10,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,140.000000,2023-08-18,0 days 09:30:00,2023-08-18 09:30:00,0.964918,10.000000
11,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,141.419998,2023-08-21,0 days 09:30:00,2023-08-21 09:30:00,0.974705,11.000000
12,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,142.660004,2023-08-22,0 days 09:30:00,2023-08-22 09:30:00,0.983252,12.000000
13,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,141.720001,2023-08-23,0 days 09:30:00,2023-08-23 09:30:00,0.976773,13.000000
14,1,IBM,buy,1,2023-08-04,open,0 days 09:30:00,2023-08-04 09:30:00,145.089996,143.505005,2023-08-24,0 days 09:30:00,2023-08-24 09:30:00,0.989076,14.000000
16,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,71.397346,2022-03-09,0 days 09:30:00,2022-03-09 09:30:00,1.037550,0.729167
17,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,68.516785,2022-03-10,0 days 09:30:00,2022-03-10 09:30:00,0.995689,1.729167
18,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,72.443405,2022-03-11,0 days 09:30:00,2022-03-11 09:30:00,1.052751,2.729167
19,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,72.162376,2022-03-14,0 days 09:30:00,2022-03-14 09:30:00,1.048667,3.729167
20,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,72.794693,2022-03-15,0 days 09:30:00,2022-03-15 09:30:00,1.057856,4.729167
21,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,72.966431,2022-03-16,0 days 09:30:00,2022-03-16 09:30:00,1.060352,5.729167
22,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.536301,2022-03-17,0 days 09:30:00,2022-03-17 09:30:00,1.068633,6.729167
23,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,74.621391,2022-03-18,0 days 09:30:00,2022-03-18 09:30:00,1.084402,7.729167
24,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.731461,2022-03-21,0 days 09:30:00,2022-03-21 09:30:00,1.071469,8.729167
25,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,74.348167,2022-03-22,0 days 09:30:00,2022-03-22 09:30:00,1.080431,9.729167
26,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.832947,2022-03-23,0 days 09:30:00,2022-03-23 09:30:00,1.072944,10.729167
27,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.684624,2022-03-24,0 days 09:30:00,2022-03-24 09:30:00,1.070788,11.729167
28,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.723656,2022-03-25,0 days 09:30:00,2022-03-25 09:30:00,1.071356,12.729167
29,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.067917,2022-03-28,0 days 09:30:00,2022-03-28 09:30:00,1.061826,13.729167
30,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,72.615143,2022-03-29,0 days 09:30:00,2022-03-29 09:30:00,1.055247,14.729167
31,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.083527,2022-03-30,0 days 09:30:00,2022-03-30 09:30:00,1.062053,15.729167
32,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,73.185013,2022-03-31,0 days 09:30:00,2022-03-31 09:30:00,1.063528,16.729167
33,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,71.896957,2022-04-01,0 days 09:30:00,2022-04-01 09:30:00,1.044810,17.729167
34,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,71.959404,2022-04-04,0 days 09:30:00,2022-04-04 09:30:00,1.045717,18.729167
35,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,71.553474,2022-04-05,0 days 09:30:00,2022-04-05 09:30:00,1.039818,19.729167
36,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,69.765808,2022-04-06,0 days 09:30:00,2022-04-06 09:30:00,1.013840,20.729167
37,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,70.117096,2022-04-07,0 days 09:30:00,2022-04-07 09:30:00,1.018945,21.729167
38,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,69.859482,2022-04-08,0 days 09:30:00,2022-04-08 09:30:00,1.015201,22.729167
39,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,69.898514,2022-04-11,0 days 09:30:00,2022-04-11 09:30:00,1.015768,23.729167
40,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,70.257614,2022-04-12,0 days 09:30:00,2022-04-12 09:30:00,1.020987,24.729167
41,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,70.382515,2022-04-13,0 days 09:30:00,2022-04-13 09:30:00,1.022802,25.729167
42,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,71.069473,2022-04-14,0 days 09:30:00,2022-04-14 09:30:00,1.032785,26.729167
43,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,71.014832,2022-04-18,0 days 09:30:00,2022-04-18 09:30:00,1.031991,27.729167
44,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,70.882126,2022-04-19,0 days 09:30:00,2022-04-19 09:30:00,1.030062,28.729167
45,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,72.209213,2022-04-20,0 days 09:30:00,2022-04-20 09:30:00,1.049348,29.729167
46,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,72.560501,2022-04-21,0 days 09:30:00,2022-04-21 09:30:00,1.054453,30.729167
47,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,70.952377,2022-04-22,0 days 09:30:00,2022-04-22 09:30:00,1.031083,31.729167
48,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,69.086655,2022-04-25,0 days 09:30:00,2022-04-25 09:30:00,1.003971,32.729167
49,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,66.315376,2022-04-26,0 days 09:30:00,2022-04-26 09:30:00,0.963698,33.729167
50,1,GE,buy,1,2022-03-08,close,0 days 16:00:00,2022-03-08 16:00:00,68.813431,62.451210,2022-04-27,0 days 09:30:00,2022-04-27 09:30:00,0.907544,34.729167